//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADPineapple.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADPineapple.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete User {0}.
        /// </summary>
        internal static string ConfDeleteCaption {
            get {
                return ResourceManager.GetString("ConfDeleteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the user account {0}?.
        /// </summary>
        internal static string ConfDeleteUserMainInstruction {
            get {
                return ResourceManager.GetString("ConfDeleteUserMainInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation cannot be undone..
        /// </summary>
        internal static string ConfDeleteUserText {
            get {
                return ResourceManager.GetString("ConfDeleteUserText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrBadErrorMsgCaption {
            get {
                return ResourceManager.GetString("ErrBadErrorMsgCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred.
        /// </summary>
        internal static string ErrBadErrorMsgMainInstruction {
            get {
                return ResourceManager.GetString("ErrBadErrorMsgMainInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the problem persists, please restart the application..
        /// </summary>
        internal static string ErrBadErrorMsgText {
            get {
                return ResourceManager.GetString("ErrBadErrorMsgText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to Active Directory.
        /// </summary>
        internal static string ErrConnectionFailMainInstruction {
            get {
                return ResourceManager.GetString("ErrConnectionFailMainInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the spelling of the name. Otherwise, there might be a problem with your network connection or DNS settings..
        /// </summary>
        internal static string ErrConnectionFailText {
            get {
                return ResourceManager.GetString("ErrConnectionFailText", resourceCulture);
            }
        }
    }
}
